apiVersion: v2
name: my-jupyterhub
description: A custom Helm chart for JupyterHub on Kubernetes
type: application
version: 0.1.0
appVersion: "5.3.0"
maintainers:
  - name: Ben
    email: benh4rdy@mail.com
keywords:
  - jupyter
  - jupyterhub
  - kubernetes
home: https://jupyter.org/hub
sources:
  - https://github.com/benh4rdy/my-jupyterhub-chart