apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "my-jupyterhub.hub.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "my-jupyterhub.hub.labels" . | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.hub.replicas }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- include "my-jupyterhub.hub.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "my-jupyterhub.hub.labels" . | nindent 8 }}
        # Network access labels for JupyterHub
        hub.jupyter.org/network-access-proxy-api: "true"
        hub.jupyter.org/network-access-proxy-http: "true"
        hub.jupyter.org/network-access-singleuser: "true"
      annotations:
        # Force pod restart when config changes
        checksum/config-map: {{ include (print $.Template.BasePath "/hub-configmap.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/hub-secret.yaml") . | sha256sum }}
        {{- with .Values.commonAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      serviceAccountName: {{ include "my-jupyterhub.hub.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.securityContext | nindent 8 }}
      {{- with .Values.hub.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.hub.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- else }}
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            preference:
              matchExpressions:
              - key: hub.jupyter.org/node-purpose
                operator: In
                values:
                - core
      {{- end }}
      {{- with .Values.hub.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- else }}
      tolerations:
      - key: hub.jupyter.org/dedicated
        operator: Equal
        value: core
        effect: NoSchedule
      - key: hub.jupyter.org_dedicated
        operator: Equal
        value: core
        effect: NoSchedule
      {{- end }}
      containers:
      - name: hub
        image: "{{ .Values.hub.image.repository }}:{{ .Values.hub.image.tag }}"
        imagePullPolicy: {{ .Values.hub.image.pullPolicy }}
        args:
          - jupyterhub
          - --config
          - /usr/local/etc/jupyterhub/jupyterhub_config.py
          - --upgrade-db
        ports:
        - name: http
          containerPort: 8081
          protocol: TCP
        env:
        - name: PYTHONUNBUFFERED
          value: "1"
        - name: HELM_RELEASE_NAME
          value: {{ .Release.Name }}
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: JUPYTERHUB_COOKIE_SECRET
          valueFrom:
            secretKeyRef:
              name: hub-secret
              key: cookie.secret
        - name: CONFIGPROXY_AUTH_TOKEN
          valueFrom:
            secretKeyRef:
              name: hub-secret
              key: proxy.token
        livenessProbe:
          httpGet:
            path: /hub/health
            port: http
            scheme: HTTP
          initialDelaySeconds: 300
          periodSeconds: 10
          failureThreshold: 30
          timeoutSeconds: 3
        readinessProbe:
          httpGet:
            path: /hub/health
            port: http
            scheme: HTTP
          periodSeconds: 2
          failureThreshold: 1000
          timeoutSeconds: 1
        securityContext:
          runAsUser: 1000
          runAsGroup: 1000
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
        resources:
          {{- toYaml .Values.hub.resources | nindent 10 }}
        volumeMounts:
        - name: config
          mountPath: /usr/local/etc/jupyterhub/jupyterhub_config.py
          subPath: jupyterhub_config.py
        - name: config
          mountPath: /usr/local/etc/jupyterhub/z2jh.py
          subPath: z2jh.py
        - name: config
          mountPath: /usr/local/etc/jupyterhub/config/
        - name: secret
          mountPath: /usr/local/etc/jupyterhub/secret/
        - name: hub-db-dir
          mountPath: /srv/jupyterhub
      volumes:
      - name: hub-db-dir
        persistentVolumeClaim:
          claimName: {{ include "my-jupyterhub.hub.fullname" . }}-db-dir
      - name: config
        configMap:
          name: {{ include "my-jupyterhub.hub.fullname" . }}
      - name: secret
        secret:
          secretName: hub-secret
      {{- if .Values.hub.extraVolumes }}
      {{- .Values.hub.extraVolumes | toYaml | nindent 6 }}
      {{- end }}
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}