apiVersion: v1
kind: Secret
metadata:
  name: {{ include "my-jupyterhub.hub.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "my-jupyterhub.config.labels" . | nindent 4 }}
    {{- include "my-jupyterhub.owner.labels" . | nindent 4 }}
    {{- include "my-jupyterhub.environment.labels" . | nindent 4 }}
    app.kubernetes.io/component: hub-secret
  annotations:
    {{- include "my-jupyterhub.secret.annotations" . | nindent 4 }}
    {{- include "my-jupyterhub.lifecycle.annotations" . | nindent 4 }}
type: Opaque
stringData:
  proxy.token: {{ include "my-jupyterhub.proxy.secretToken" . }}
  cookie.secret: {{ randAlphaNum 32 | b64enc | quote }}