{{/*
Image Pull Secrets Template
This template creates Docker registry credentials for private image registries
*/}}

{{- if .Values.global.imagePullSecrets }}
{{- range .Values.global.imagePullSecrets }}
{{- if and .registry .username .password }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name | required "imagePullSecret name is required" }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "my-jupyterhub.labels" $ | nindent 4 }}
    app.kubernetes.io/component: registry-credentials
  {{- with $.Values.global.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ printf `{"auths":{"%s":{"username":"%s","password":"%s","email":"%s","auth":"%s"}}}` .registry .username .password (.email | default "noreply@example.com") (printf "%s:%s" .username .password | b64enc) | b64enc }}
{{- end }}
{{- end }}
{{- end }}

{{/*
Alternative: Support for pre-existing secrets
If users prefer to create secrets manually or via external tools
*/}}
{{- if .Values.global.existingImagePullSecrets }}
# Note: The following secrets should be created manually:
{{- range .Values.global.existingImagePullSecrets }}
# kubectl create secret docker-registry {{ .name }} \
#   --docker-server={{ .registry }} \
#   --docker-username={{ .username }} \
#   --docker-password={{ .password }} \
#   --docker-email={{ .email | default "noreply@example.com" }} \
#   --namespace={{ $.Release.Namespace }}
{{- end }}
{{- end }}

{{/*
ServiceAccount patch to add image pull secrets
This ensures all pods can pull from private registries
*/}}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "my-jupyterhub.hub.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "my-jupyterhub.hub.labels" . | nindent 4 }}
  {{- with .Values.hub.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- if or .Values.global.imagePullSecrets .Values.global.existingImagePullSecrets }}
imagePullSecrets:
{{- if .Values.global.imagePullSecrets }}
{{- range .Values.global.imagePullSecrets }}
{{- if .name }}
  - name: {{ .name }}
{{- end }}
{{- end }}
{{- end }}
{{- if .Values.global.existingImagePullSecrets }}
{{- range .Values.global.existingImagePullSecrets }}
  - name: {{ .name }}
{{- end }}
{{- end }}
{{- end }}

{{- if .Values.singleuser.serviceAccount.create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.singleuser.serviceAccount.name | default "singleuser" }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "my-jupyterhub.labels" . | nindent 4 }}
    app.kubernetes.io/component: singleuser
  {{- with .Values.singleuser.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- if or .Values.global.imagePullSecrets .Values.global.existingImagePullSecrets }}
imagePullSecrets:
{{- if .Values.global.imagePullSecrets }}
{{- range .Values.global.imagePullSecrets }}
{{- if .name }}
  - name: {{ .name }}
{{- end }}
{{- end }}
{{- end }}
{{- if .Values.global.existingImagePullSecrets }}
{{- range .Values.global.existingImagePullSecrets }}
  - name: {{ .name }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}